/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clasevisual2.ui;

import clasevisual2.objetos.Persona;
import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author Hugo Chanampe
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        bgFuente.add(jrbCursiva);
        bgFuente.add(jrbNegrita);
        bgFuente.add(jrbNegritaCursiva);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgFuente = new javax.swing.ButtonGroup();
        jtfNombre = new javax.swing.JTextField();
        jtfApellido = new javax.swing.JTextField();
        jtfDocumento = new javax.swing.JTextField();
        jtfEdad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbMostrar = new javax.swing.JButton();
        jlMostrar = new javax.swing.JLabel();
        jcbCursiva = new javax.swing.JCheckBox();
        jcbNegrita = new javax.swing.JCheckBox();
        jrbCursiva = new javax.swing.JRadioButton();
        jrbNegrita = new javax.swing.JRadioButton();
        jrbNegritaCursiva = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido");

        jLabel3.setText("Documento");

        jLabel4.setText("Edad");

        jbMostrar.setText("Mostrar");
        jbMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMostrarActionPerformed(evt);
            }
        });

        jcbCursiva.setText("Cursiva");
        jcbCursiva.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbCursivaItemStateChanged(evt);
            }
        });

        jcbNegrita.setText("Negrita");
        jcbNegrita.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbNegritaItemStateChanged(evt);
            }
        });

        jrbCursiva.setText("Cursiva");
        jrbCursiva.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jrbCursivaItemStateChanged(evt);
            }
        });

        jrbNegrita.setText("Negrita");
        jrbNegrita.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jrbNegritaItemStateChanged(evt);
            }
        });

        jrbNegritaCursiva.setText("Negrita-Crusiva");
        jrbNegritaCursiva.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jrbNegritaCursivaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbMostrar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                .addComponent(jtfApellido)
                                .addComponent(jtfDocumento)
                                .addComponent(jtfEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jlMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jrbCursiva)
                            .addComponent(jcbCursiva))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbNegrita)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jrbNegrita)
                                .addGap(18, 18, 18)
                                .addComponent(jrbNegritaCursiva)))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbCursiva)
                    .addComponent(jcbNegrita))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbCursiva)
                    .addComponent(jrbNegrita)
                    .addComponent(jrbNegritaCursiva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlMostrar)
                .addGap(31, 31, 31)
                .addComponent(jbMostrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMostrarActionPerformed
        // TODO add your handling code here:
        Persona persona = new Persona();
        persona.setApellido(jtfApellido.getText());
        persona.setNombre(jtfNombre.getText());
        persona.setDocumento(Integer.parseInt(jtfDocumento.getText()));
        persona.setEdad(Integer.parseInt(jtfEdad.getText()));
        
       // jlMostrar.setText(persona.toString());
        
        JOptionPane.showMessageDialog(null,persona,"Mi Primer Mensaje",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jbMostrarActionPerformed

    private void jcbNegritaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbNegritaItemStateChanged
        // TODO add your handling code here:
        Font fuente=null;
        
        if(jcbNegrita.isSelected() && jcbCursiva.isSelected())
            fuente = new Font("Serif", Font.BOLD + Font.ITALIC, 14);
        else if(jcbNegrita.isSelected())
            fuente = new Font("Serif", Font.BOLD, 14);
        else if(jcbCursiva.isSelected())
            fuente = new Font("Serif", Font.ITALIC, 14);
        else
            fuente = new Font("Serif", Font.PLAIN, 14);
        
        jtfApellido.setFont(fuente);
        jtfNombre.setFont(fuente);
        jtfDocumento.setFont(fuente);
        jtfEdad.setFont(fuente);
    }//GEN-LAST:event_jcbNegritaItemStateChanged

    private void jcbCursivaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbCursivaItemStateChanged
        // TODO add your handling code here:
         Font fuente=null;
        
          if(jcbNegrita.isSelected() && jcbCursiva.isSelected())
            fuente = new Font("Serif", Font.BOLD + Font.ITALIC, 14);
          else if(jcbCursiva.isSelected())
            fuente = new Font("Serif", Font.ITALIC, 14);
          else if(jcbNegrita.isSelected())
            fuente = new Font("Serif", Font.BOLD, 14);
          else
            fuente = new Font("Serif", Font.PLAIN, 14);
        
        jtfApellido.setFont(fuente);
        jtfNombre.setFont(fuente);
        jtfDocumento.setFont(fuente);
        jtfEdad.setFont(fuente);
    }//GEN-LAST:event_jcbCursivaItemStateChanged

    private void jrbNegritaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jrbNegritaItemStateChanged
        // TODO add your handling code here:
        
        Font fuente = new Font("Serif", Font.BOLD, 14);
        jtfApellido.setFont(fuente);
        jtfNombre.setFont(fuente);
        jtfDocumento.setFont(fuente);
        jtfEdad.setFont(fuente);
    }//GEN-LAST:event_jrbNegritaItemStateChanged

    private void jrbCursivaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jrbCursivaItemStateChanged
        // TODO add your handling code here:
       Font fuente = new Font("Serif", Font.ITALIC, 14);
       jtfApellido.setFont(fuente);
        jtfNombre.setFont(fuente);
        jtfDocumento.setFont(fuente);
        jtfEdad.setFont(fuente);
    }//GEN-LAST:event_jrbCursivaItemStateChanged

    private void jrbNegritaCursivaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jrbNegritaCursivaItemStateChanged
        // TODO add your handling code here:
        Font fuente = new Font("Serif", Font.BOLD + Font.ITALIC, 14);
        jtfApellido.setFont(fuente);
        jtfNombre.setFont(fuente);
        jtfDocumento.setFont(fuente);
        jtfEdad.setFont(fuente);
    }//GEN-LAST:event_jrbNegritaCursivaItemStateChanged

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgFuente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbMostrar;
    private javax.swing.JCheckBox jcbCursiva;
    private javax.swing.JCheckBox jcbNegrita;
    private javax.swing.JLabel jlMostrar;
    private javax.swing.JRadioButton jrbCursiva;
    private javax.swing.JRadioButton jrbNegrita;
    private javax.swing.JRadioButton jrbNegritaCursiva;
    private javax.swing.JTextField jtfApellido;
    private javax.swing.JTextField jtfDocumento;
    private javax.swing.JTextField jtfEdad;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables
}
